services:
  mysql:
    image: mysql:8.0
    container_name: ggungsil-db
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: ggungsil
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_unicode_ci
      TZ: Asia/Seoul
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    image: maruhan/wonnit:latest
    container_name: wonnit-app
    env_file:
      - .env
    ports:
      - "8080:8080"
    environment:
      TZ: Asia/Seoul
    depends_on:
      - mysql

volumes:
  mysql_data: