spring:
  cloud:
    aws:
      region:
        static: ap-northeast-2
      s3:
        bucket: wonnit
      credentials:
        access-key: ${AWS_S3_ACCESSKEY}
        secret-key: ${AWS_S3_SECRETKEY}
